### ISSUE TITLE
Cannot update the container image of batch/v1 Job

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener-resource-manager#121]
**How to categorize this issue?**

/kind enhancement
/priority normal

**What would you like to be added**:

There was an issue with a Gardener Shoot most likely caused by the GRM.
Apparently, there is some merging logic when reconciling an existing resource with an updated resource.

In the logs below, you can see that the managed resource was unhealthy and that the batch/v1 Job had an invalid **spec** when applying it to the target cluster.

```
Network extension (shoot--dxp--trial/trial) reports failing health check: Health check summary: 1/1 unsuccessful, 0/1 progressing, 0/1 successful. Unsuccessful checks: 1) ManagedResourceUnhealthy: managed resource extension-networking-cilium-config in namespace shoot--dxp--trial is unhealthy: condition "ResourcesApplied" has invalid status False (expected True) due to ApplyFailed: Could not apply all new resources: 1 error occurred: error during apply of object "batch/v1/Job/kube-system/hubble-generate-certs": Job.batch "hubble-generate-certs" is invalid: spec.template: 
```
The issue got resolved after deleting the existing batch/v1 Job in the target cluster. This indicates that there is some problem with the merge of the existing and updated resource.

**Why is this needed**:

**Comment by timebertt** [comment]
Do you have the rest of the error message? Especially the part after `is invalid: spec.template:` would be interesting.
Steps to reproduce would also be fine, if you don't have the error message anymore.

**Comment by ialidzhikov** [comment]
Okay, after few hours I finally managed to reproduce the issue. 
The Jobs spec in https://raw.githubusercontent.com/gardener/gardener-extension-networking-cilium/v1.5.0/charts/internal/cilium/charts/hubble-relay/templates/job.yaml is obviously correct and valid.

So this issue happens when the container image that the Job refers is changed.

Steps to reproduce would be:

1. Create Shoot with cilium and hubble enabled:

```yaml
  networking:
    providerConfig:
      apiVersion: cilium.networking.extensions.gardener.cloud/v1alpha1
      hubble:
        enabled: true
      kind: NetworkConfig
    type: cilium
    pods: 10.223.128.0/17
    nodes: 10.222.0.0/16
    services: 10.223.0.0/17
```

2. Update the networking-cilium ctrlreg with imageVectorOverwrite to overwrite for the job image

```yaml
      values:
        imageVectorOverwrite: |
          images:
          - name: certgen
            repository: quay.io/cilium/certgen
            tag: v0.1.2
```

3. Make sure that the corresponding MR cannot be applied

```
$ k -n shoot--foo--bar get mr extension-networking-cilium-config
NAME                                 CLASS   APPLIED   HEALTHY   AGE
extension-networking-cilium-config           False     True      79m
```

So obviously `.spec.template` is immutable. The update of the Job fails with

```
The Job "hubble-generate-certs" is invalid: spec.template: Invalid value: [...] field is immutable
```
