### ISSUE TITLE
Resources created with default namespace aren't deleted

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener-resource-manager#7]
Let's look at the following example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: managedresource-example2
  namespace: default
type: Opaque
data:
  other-objects.yaml: YXBpVmVyc2lvbjogYXBwcy92MSAjIGZvciB2ZXJzaW9ucyBiZWZvcmUgMS45LjAgdXNlIGFwcHMvdjFiZXRhMgpraW5kOiBEZXBsb3ltZW50Cm1ldGFkYXRhOgogIG5hbWU6IG5naW54LWRlcGxveW1lbnQKICBuYW1lc3BhY2U6IGRlZmF1bHQKc3BlYzoKICBzZWxlY3RvcjoKICAgIG1hdGNoTGFiZWxzOgogICAgICBhcHA6IG5naW54CiAgcmVwbGljYXM6IDIgIyB0ZWxscyBkZXBsb3ltZW50IHRvIHJ1biAyIHBvZHMgbWF0Y2hpbmcgdGhlIHRlbXBsYXRlCiAgdGVtcGxhdGU6CiAgICBtZXRhZGF0YToKICAgICAgbGFiZWxzOgogICAgICAgIGFwcDogbmdpbngKICAgIHNwZWM6CiAgICAgIGNvbnRhaW5lcnM6CiAgICAgIC0gbmFtZTogbmdpbngKICAgICAgICBpbWFnZTogbmdpbng6MS43LjkKICAgICAgICBwb3J0czoKICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDgwCg==
    # apiVersion: apps/v1
    # kind: Deployment
    # metadata:
    #   name: nginx-deployment
    # spec:
    #   selector:
    #     matchLabels:
    #       app: nginx
    #   replicas: 2 # tells deployment to run 2 pods matching the template
    #   template:
    #     metadata:
    #       labels:
    #         app: nginx
    #     spec:
    #       containers:
    #       - name: nginx
    #         image: nginx:1.7.9
    #         ports:
    #         - containerPort: 80
```

The `Deployment` is a namespaced resource but has no namespace specified in the `metadata` section. Consequently, the `Gardener-Resource-Manager` creates the resource with the default namespace either specified in the `target` Kubeconfig or by the `in-cluster` config via the mounted `ServiceAccount` (/var/run/secrets/kubernetes.io/serviceaccount/namespace).

Furthermore, the `Deployment` is written to the `status` of the `ManagedResource` but without any `namespace` information. After that the `Gardener-Resource-Manager` is not able to delete the resource any more.

To solve the issue we have to address two challenges:
1.) Dynamically find out what namespace is used when applying the resource or set it via a command line flag, e.g. `--default-namespace`.
~2.) If the resource has no namespace specified, find out if it's a namespaced resource at all and set the `namespace` from 1.) if applicable. Therefore, we'd need to use a `DiscoveryClient`.~
